version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: library
    volumes:
      - postgres_data:/var/lib/postgresql/data

  goservices-book:
    build: "."
    container_name: goservices-book
    image: naufalhakm/library-api-book:v4
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: user
      DB_PASSWORD: password
      DB_DATABASE: library
    ports:
      - "8081:8081"
      - "50051:50051"
    restart: always

volumes:
  postgres_data:

networks:
  default:
    external:
      name: nginx-proxy